### ISSUE TITLE
Filter to change path

### ISSUE THREAD

**Issue by radeno** [fahrirusliyadi/fr-thumbnails-folder#1]
Hello,
I like your module, it is very handy for ugly wordpress thumbnail generation.

I have one issue. do you plan to add filter ability into "modify_filename" method?
Because there are 2 two cases how to create thumbnail folder.

First is prepend all thumbnails with folder name "thumbnails" on begin of path. as your plugin do. Or second posibility is to append "thumbnail" or another custom folder name eg. "versions" etc on end of path. For example /uploads/2018/01/thumbnails.

Regards!

**Comment by radeno** [comment]
Something like that:

```
$new_filename = apply_filters('fr_thumbnails_modify_filename', $new_filename, $upload_dir, $generated_filename);
```

**Comment by fahrirusliyadi** [comment]
Sounds good. But I think you don't need to pass `$upload_dir` to the filter callbacks.

**Comment by radeno** [comment]
Your are right. it should be re-called in filter method.
My example is just quick prototype :)
