### ISSUE TITLE
Release 1.3

### ISSUE THREAD

**Issue by radeno** [fahrirusliyadi/fr-thumbnails-folder#2]
Hi again!

when do you plan to release version 1.3 which allows filter output pathname?
For now i (and maybe other) just use master branch, but official released version will be better :)

Regards!

**Comment by fahrirusliyadi** [comment]
Hi,

I'm planning to add WP-CLI command to delete all existing thumbnails before releasing version 1.3.0. But I haven't got time to work on it. Perhaps in next few days.
