### ISSUE TITLE
Thumbnails are not generated properly except thumbnail size

### ISSUE THREAD

**Issue by radeno** [fahrirusliyadi/fr-thumbnails-folder#3]
Hello,

i have this issue because FR Thumbnails Folder at it is very weird situation. I can't simulate it properly.
But i will be as specific as can to describe it.

When i upload image thru Media (or content editor) it just makes only "thumbnail" size and no more.
After uploading it returns small thumbnail as <img> tag but in console i see infinite looping or wp-ajax.php request with this response:
```json
{"success":true,"data":{"progress":-1,"current":-1,"total":-1}}
```
Tested with only this plugin and without any theme active.

Thumbnails for PDF are generated properly (WP 4.7 support), because they are skipped by this plugin.

My env:
Wordpress: 4.9.5
PHP: 7.2.4
Apache: 2.4.33

**Comment by fahrirusliyadi** [comment]
I can't reproduce this issue. Please provide the steps to reproduce it. Based on your description, this is what I tried:

1. Install WordPress 4.9.5.
1. Install Fr Thumbnails Folder 1.3.0.
1. Upload an image from Media Library. The thumbnail, medium and large image sizes are properly generated in  `wp-content/uploads/thumbnails/2018/04` folder.

> `{"success":true,"data":{"progress":-1,"current":-1,"total":-1}}`

Please provide more information about this, like the request method, request url, request paramaters, in which page does this happen, and anything relevant.

**Comment by fahrirusliyadi** [comment]
I’m closing this issue because it has been inactive for a few months. Please reopen if you still encounter this issue.
