### ISSUE TITLE
Timber compatibility

### ISSUE THREAD

**Issue by jbjanot** [fahrirusliyadi/fr-thumbnails-folder#4]
Hi and thanks for this super useful plugin!
This a functionality that I wanted for a long time but never had the chance to find something working nicely until now.

My problem, as the title implied, is that I rely heavily on [Timber](https://github.com/timber/timber/) to run my WordPress websites.
Do you think there is a way to make your plugin compatible with Timber ?
As for now, it is not the case, the thumbnails of Timber keep generating in the same folder as the source image.

Your insight on this would be much appreciated!
Have a nice day and thanks for your help!

**Comment by fahrirusliyadi** [comment]
Hi, I cannot reproduce the issue. I have tried to install [Timber](https://wordpress.org/plugins/timber-library/) and [Timber Starter Theme](https://github.com/timber/starter-theme). Then upload an image to the media library, the thumbnails are correctly generated in the thumbnails folder.

**Comment by jbjanot** [comment]
Thank you @fahrirusliyadi for having a look at it and taking the time to install Timber.
Sorry for my lack of detail. The problem arise when an image is generated with the Timber Image Helper, like in [this example](https://timber.github.io/docs/reference/timber-imagehelper/#resize).

Would you mind trying to test this?

Thank you for the time already spent on this.

**Comment by fahrirusliyadi** [comment]
Unfortunately, Timber uses a custom algorithm to generate the image. This plugin only supports thumbnails that are generated using WordPress functions.

**Comment by jbjanot** [comment]
Ok thanks again for having a look at it!
