### ISSUE TITLE
Very slow Media page (and I assume, image_size query in general)

### ISSUE THREAD

**Issue by rsepierre** [fahrirusliyadi/fr-thumbnails-folder#5]
I get a ~30 seconds ajax loading time for the media library when the plugin is active.
It loads 80 thumbnails URLs (almost 0.5seconds per single image size url)
Maybe I am wrong but I assume it is because we use str_replace for every image query

`$image_url  = str_replace($upload_dir['basedir'], $upload_dir['baseurl'], $image_size['path']);`

I also assume that the fact that we store the full path which is not default behavior according to the comments on `-resizer.php` forces us to use str_replace instead of join and also makes it quite a long string to `str_replace`.

>          * Let's keep the `path` from the metadata. We will use this path to get the 
>          * image URL and to delete the image.
>          * The original behavior removes the `path`. 

I'm sure there should be a way to get the URL without doing any `str_replace` if we changed how we store the original data we should be able to join $upload_dir['baseurl'] + 'thumbnails' + $image_size['path']);

But because it's affecting every function from saving image to storing data and retrieving URLs, and I don't have a clear picture of what variables store what I am not able to decipher how to move forward on a fix.

If we ignore this issue, I think the plugin's function should be default wordpress behaviour. It makes so much sense and I am astounded that it is the only plugin that does this.

**Comment by rsepierre** [comment]
Actually I figured it out. The reason the media library is slow is the "maybe_generate_intermediate_image" method. 
If the required media is of higher resolution than the original, it will load the image editor every time. I'm working on a fix and will keep you updated

**Comment by rsepierre** [comment]
[https://github.com/fahrirusliyadi/fr-thumbnails-folder/compare/master...rsepierre:fr-thumbnails-folder:master](https://github.com/fahrirusliyadi/fr-thumbnails-folder/compare/master...rsepierre:fr-thumbnails-folder:master)

I have made a temporary fix. This works for me because none of my image_sizes use 'crop'. But essentially I check if wanted_size['width'] is bigger than original ['width'] before calling the resizer class and image editor. This made the media library load in about 3 seconds instead of 30 but still generate image sizes if they were never created before. There might be a better fix than this, I don't consider my commit to be production ready.

**Comment by fahrirusliyadi** [comment]
Hi @rsepierre, isn't it enough to just edit the `set_wanted_size()` method like this?


```diff
    protected function set_wanted_size() {
        $additional_image_sizes = wp_get_additional_image_sizes();
        
        $width  = 0;
        $height = 0;
        $crop   = false;

        if (isset($additional_image_sizes[$this->args['size']])) {
            $width  = $additional_image_sizes[$this->args['size']]['width'];
            $height = $additional_image_sizes[$this->args['size']]['height'];
            $crop   = isset($additional_image_sizes[$this->args['size']]['crop'] ) ? $additional_image_sizes[$this->args['size']]['crop'] : false;
        } else if (in_array($this->args['size'], array('thumbnail', 'medium', 'large'))) {
            $width  = get_option($this->args['size'] . '_size_w');
            $height = get_option($this->args['size'] . '_size_h');
            $crop   = ('thumbnail' === $this->args['size']) ? (bool) get_option('thumbnail_crop') : false;
        } else {
            return;
        }

-       if (!$width && !$height) {
+       if ((!$width && !$height) || ($width >= $this->metadata['width'] || $height >= $this->metadata['height'])) {
            return;
        }
        
        $this->wanted_size = array(
            'width'     => $width,
            'height'    => $height,
            'crop'      => $crop,
        );
    }
```

**Comment by rsepierre** [comment]
After testing, this still gets me a ~30 seconds page load for about 80 images in the default wordpress library. But this would be the case with any image load. I have not looked at the code for the last three weeks. But I actually believe that even if you only fetch a 250px thumbnail, the extension will somehow check if the image has all sizes and try to generate them if they don't exist. If your image is smaller than some images sizes as defined in your configuration. Each time you call any size of that image, the editor will be running for each sizes with higher resolution that your image. 

(again I am not 100% sure about this because I forgot what I tested a few weeks ago).

The idea with my "fix" is to introduce a "wanted_size" argument. If wanted size bigger than original : skip.

**Comment by rsepierre** [comment]
Hello @fahrirusliyadi and thank you for coming back to me.

After testing the suggested fix, this still gets me a ~45 seconds page load for about 80 images in the default wordpress library.

With my commit - which is not ready for production as it is, but fine for my use case as of now - the loading is around ~4 seconds on the same machine.

I have not looked at the code for the last three weeks so my memories are not perfectly fresh. But I believe that even if you only fetch a 250px thumbnail, the extension will somehow check if the image has all sizes and try to generate all the missing sizes on the fly. But if your original image is smaller than some images sizes defined in your wordpress configuration it is expected that those images don't exist, every time and at every call. Yet, each time you call any size of that image, the image editor will be running for each sizes defined in wordpress that has higher resolution than your original image. 

(again I am not 100% sure this is the exact behavior but this is what I remember from a few weeks ago).

Essentially, the fix is not in the `set_wanted_size()` method - or `get_wanted_size()` in my case.
The fix is in the `maybe_generate_intermediate_image()` method which we definitely want to get out of before the  `new Fr_Thumbnails_Folder_Image_Resizer` call as often as as possible.

this is the important part, except that in my case I only check for width and nothing else. But if cropped sizes are defined, it would create exceptions that would require additional checks

> `includes/class-fr-thumbnails-folder-image-sizes.php`

![image](https://github.com/user-attachments/assets/2f43f565-31e3-4bc6-94f6-a093dc286031)

**Comment by fahrirusliyadi** [comment]
Hi @rsepierre,

Could you provide detailed steps to reproduce it? Perhaps I'm missing something here. Here is what I tried:

- Setting the large size larger than the actual images
   ![image](https://github.com/user-attachments/assets/3b7e1419-2464-4c23-b535-ce750adcd6ef)
- The plugin only generates thumbnails & medium sizes
   ![image](https://github.com/user-attachments/assets/8a09e9e5-a681-40c2-af38-27f82b743bef)
- It does slow when opening the library (4.3 s)
   ![Screenshot 2024-09-22 at 08 03 13](https://github.com/user-attachments/assets/e3187693-74e4-406f-bbb1-cdaa1f89e72c)
- After not setting the wanted size, it reduced to 353 ms. By not setting the wanted size, it is essentially canceling the resizing process.
   ![Screenshot 2024-09-22 at 08 01 59](https://github.com/user-attachments/assets/6fe44f97-9a38-4fea-8bef-258657626d8d)

**Comment by rsepierre** [comment]
I am not sure what exactly is the difference between your two screenshots on the back-end ?
Which screenshot is running what commit of your plugin ?


This is my setup for images in my wordpress installation : 
I want lots of image sizes so that the user only downloads an image size close to what is desired in the front-end. The goal is to reduce loading times but keep the high quality if we need it. I generally have high resolution original images but it would be a waste to download high resolution on a small laptop screen or a phone.

This is not necessarily relevant here but the idea is that I use lazy loading so that every images originally shows a blurred 25*25px image while it's loading the "perfect size" for the user screen from that list of image sizes. All of this is handled via `srcset ` and `sizes` attributes in the front-end and the lazysizes javascript library.


the section of my `function.php` file dedicated to images :
```
	// Remove unecessary wordpress stuff
	add_filter( 'big_image_size_threshold', '__return_false' );
	add_filter( 'wp_image_maybe_exif_rotate', '__return_zero', 10, 2 );
	remove_image_size( '1536x1536');
	remove_image_size( '2048x2048');

	// Set image sizes
	add_image_size( '_25', 25, 0 );				// 25 (Preload)
	update_option( 'thumbnail_size_w', 160 ); 	// 160 (Thumbnails)
	update_option( 'thumbnail_size_h', 0 );
	update_option( 'thumbnail_crop', 0 );
	add_image_size( '_265', 265, 0 ); 			// 265
	update_option( 'medium_size_w', 512 ); 		// 512
	update_option( 'medium_size_h', 0 );
	update_option( 'medium_large_size_h', 0 );	// 768 (default width)
	add_image_size( '_1024', 1024, 0 );			// 1024
	add_image_size( '_1280', 1280, 0 );			// 1280 (HD)
	add_image_size( '_1540', 1540, 0 );			// 1540
	add_image_size( '_1920', 1920, 0 );			// 1920 (FULL HD)
	add_image_size( '_2560', 2560, 0 );			// 2560 (WQHD)
	add_image_size( '_3200', 3200, 0 );			// 3200
	add_image_size( '_3840', 3840, 0 );			// 3840 (4k)
	update_option( 'large_size_w', 5120 );		// 5120 (5k)
	update_option( 'large_size_h', 0 );
```

So if I upload an image of size "1000x1000" it will have to "ignore" about 7 image sizes that have higher resolution than the original and do not need to be generated (1024, 1280, 1540, 1920, 2560, 3200, 3840, 5120).

I think that the original plugin code will, for every one of those sizes, open the image editor class with `new Fr_Thumbnails_Folder_Image_Resizer`, even if we are in the wordpress library which should only use the "thumbnail" image size. It will also do this every time the image is requested (not only when uploading the file).

Here is what I think happens : 
- an image file is requested (whether it's in the wordpress media library or in the front end)
- it checks if all the created sizes of that images matches the wordpress image-sizes list
- because a 1000x1000 image does not need to generate all those images sizes, it find that indeed, 7 images files do not exist. All those files are missing.
- The way your addon is written means that it instantly runs `new Fr_Thumbnails_Folder_Image_Resizer` even if the missing image files does not need to be generated. This opens up the images editor. Later it figures that it doesn't actually need to generate that image size and then does nothing.
- this will happen on every loading of every images that have sizes that do not need to be generated.

The end result is OK. The image file generated are OK, and none of the unnecessary images files are created. The "final behavior" is OK. But it is very very very slow as I explained it takes around 43 seconds for wordpress to show the media library page with all 80 high resolution images and lots of image sizes so around 0.5 second per image.

So I made the commit I send you on the 24th of august that checks if the size requested is bigger than the original, and skips opening the image editor entirely when it is the case. This reduces load time by 90% because it never runs `new Fr_Thumbnails_Folder_Image_Resizer` if it does not need to.

This is the important part of the commit I made. All the rest is moving code around so that we have the ability to check the wanted size from within the `maybe_generate_intermediate_image`
![image](https://github.com/user-attachments/assets/72d4b322-fe6f-4db5-99d9-4e2d045ceabb)

https://github.com/fahrirusliyadi/fr-thumbnails-folder/compare/master...rsepierre:fr-thumbnails-folder:master

**Comment by fahrirusliyadi** [comment]
The first screenshot uses code from the master branch, you can see the time to load the data. 

The second screenshot uses code from https://github.com/fahrirusliyadi/fr-thumbnails-folder/issues/5#issuecomment-2335103068. It will not load `wp_get_image_editor` which causes the performance issue when not needed. I've edited the condition, previously it wasn't working for you because you are using 0 height which I didn't test, and it should work now.

**Comment by rsepierre** [comment]
Sorry I did not see you edited the code in the comment. This does work indeed and it's a better way of fixing the issue.

I have found another issue recently in the plugin with SVG files. It seems to manifest itself both in your fix and my fix for the previous issue, because we check for the image width/height metadata and SVGs don't have any.

![image](https://github.com/user-attachments/assets/e8f86519-ec9e-41c9-978e-7b9e62d83e8e)

I fixed it locally in the same logic I did with the previous issue by adding this bit of code to the maybe_generate_image() method: 

```
        if (get_post_mime_type($id) === 'image/svg+xml') {
            return $downsize;
        }
```

But it may make more sense to fix it in set_wanted_size() since your snippets works to fix the slow media page issue.
You may also prefer to exclude every file with no "width/height" metadata rather than excluding based on SVG MIME type the way I did.

_Arguably, I would also consider disabling resizing on GIFs simply because their main use today is for animation and resizing makes them still. But this is a completely different topic and debatable. It's also definitely not a bug._

**Comment by fahrirusliyadi** [comment]
![image](https://github.com/user-attachments/assets/baa2a658-4b0e-4cf6-80a7-1a519ff8be96)

Unfortunately, WordPress currently doesn't support SVG images. For this reason, I won't be supporting it. However, I've implemented additional checks for that error.

The GIF format seems to be a WordPress-specific issue, and there's a chance it might be addressed in future WordPress updates, so I won't be supporting it either.
